// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {contracts} from '../models';

export function ArchiveCreateZIP(arg1:string,arg2:Array<string>):Promise<contracts.ToolResult_string_>;

export function ArchiveExtractZIP(arg1:string,arg2:string):Promise<contracts.ToolResult_string_>;

export function ArchiveZIPInfo(arg1:string):Promise<contracts.ToolResult___nexatools_internal_core_archive_ZIPEntry_>;

export function CalcAddDays(arg1:string,arg2:number):Promise<contracts.ToolResult_string_>;

export function CalcBasic(arg1:string,arg2:number,arg3:number):Promise<contracts.ToolResult_float64_>;

export function CalcDateDiff(arg1:string,arg2:string):Promise<contracts.ToolResult_int_>;

export function CalcISOToTimestamp(arg1:string):Promise<contracts.ToolResult_int64_>;

export function CalcNumberBase(arg1:string,arg2:number,arg3:number):Promise<contracts.ToolResult_string_>;

export function CalcPercentage(arg1:string,arg2:number,arg3:number):Promise<contracts.ToolResult_float64_>;

export function CalcTimestampToISO(arg1:number):Promise<contracts.ToolResult_string_>;

export function CalcUnit(arg1:string,arg2:number,arg3:string,arg4:string):Promise<contracts.ToolResult_float64_>;

export function Greet(arg1:string):Promise<string>;

export function ListTools():Promise<contracts.ToolResult___nexatools_internal_infra_toolregistry_Tool_>;

export function QRGenerateBarcodeSVG(arg1:string,arg2:string,arg3:string):Promise<contracts.ToolResult_string_>;

export function QRGeneratePNG(arg1:string,arg2:number,arg3:string):Promise<contracts.ToolResult_string_>;

export function QRReadFromImage(arg1:string):Promise<contracts.ToolResult_string_>;

export function SecurityHashFile(arg1:string,arg2:string):Promise<contracts.ToolResult_string_>;

export function SecurityHashText(arg1:string,arg2:string):Promise<contracts.ToolResult_string_>;

export function SecurityPassword(arg1:number,arg2:boolean,arg3:boolean,arg4:boolean,arg5:boolean):Promise<contracts.ToolResult_string_>;

export function TextBase64Decode(arg1:string):Promise<contracts.ToolResult_string_>;

export function TextBase64Encode(arg1:string):Promise<contracts.ToolResult_string_>;

export function TextCSVToJSON(arg1:string):Promise<contracts.ToolResult_string_>;

export function TextConvertCase(arg1:string,arg2:string):Promise<contracts.ToolResult_string_>;

export function TextFormatJSON(arg1:string,arg2:string):Promise<contracts.ToolResult_string_>;

export function TextJSONToCSV(arg1:string):Promise<contracts.ToolResult_string_>;

export function TextLorem(arg1:number,arg2:number,arg3:number):Promise<contracts.ToolResult_string_>;

export function TextMinifyJSON(arg1:string):Promise<contracts.ToolResult_string_>;

export function TextSlug(arg1:string):Promise<contracts.ToolResult_string_>;

export function TextURLDecode(arg1:string):Promise<contracts.ToolResult_string_>;

export function TextURLEncode(arg1:string):Promise<contracts.ToolResult_string_>;

export function TextWordCount(arg1:string):Promise<contracts.ToolResult_nexatools_internal_core_text_WordStats_>;
