// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveCreateZIP(arg1, arg2) {
  return window['go']['bindings']['App']['ArchiveCreateZIP'](arg1, arg2);
}

export function ArchiveExtractZIP(arg1, arg2) {
  return window['go']['bindings']['App']['ArchiveExtractZIP'](arg1, arg2);
}

export function ArchiveZIPInfo(arg1) {
  return window['go']['bindings']['App']['ArchiveZIPInfo'](arg1);
}

export function CalcAddDays(arg1, arg2) {
  return window['go']['bindings']['App']['CalcAddDays'](arg1, arg2);
}

export function CalcBasic(arg1, arg2, arg3) {
  return window['go']['bindings']['App']['CalcBasic'](arg1, arg2, arg3);
}

export function CalcDateDiff(arg1, arg2) {
  return window['go']['bindings']['App']['CalcDateDiff'](arg1, arg2);
}

export function CalcISOToTimestamp(arg1) {
  return window['go']['bindings']['App']['CalcISOToTimestamp'](arg1);
}

export function CalcNumberBase(arg1, arg2, arg3) {
  return window['go']['bindings']['App']['CalcNumberBase'](arg1, arg2, arg3);
}

export function CalcPercentage(arg1, arg2, arg3) {
  return window['go']['bindings']['App']['CalcPercentage'](arg1, arg2, arg3);
}

export function CalcTimestampToISO(arg1) {
  return window['go']['bindings']['App']['CalcTimestampToISO'](arg1);
}

export function CalcUnit(arg1, arg2, arg3, arg4) {
  return window['go']['bindings']['App']['CalcUnit'](arg1, arg2, arg3, arg4);
}

export function Greet(arg1) {
  return window['go']['bindings']['App']['Greet'](arg1);
}

export function ListTools() {
  return window['go']['bindings']['App']['ListTools']();
}

export function QRGenerateBarcodeSVG(arg1, arg2, arg3) {
  return window['go']['bindings']['App']['QRGenerateBarcodeSVG'](arg1, arg2, arg3);
}

export function QRGeneratePNG(arg1, arg2, arg3) {
  return window['go']['bindings']['App']['QRGeneratePNG'](arg1, arg2, arg3);
}

export function QRReadFromImage(arg1) {
  return window['go']['bindings']['App']['QRReadFromImage'](arg1);
}

export function SecurityHashFile(arg1, arg2) {
  return window['go']['bindings']['App']['SecurityHashFile'](arg1, arg2);
}

export function SecurityHashText(arg1, arg2) {
  return window['go']['bindings']['App']['SecurityHashText'](arg1, arg2);
}

export function SecurityPassword(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bindings']['App']['SecurityPassword'](arg1, arg2, arg3, arg4, arg5);
}

export function TextBase64Decode(arg1) {
  return window['go']['bindings']['App']['TextBase64Decode'](arg1);
}

export function TextBase64Encode(arg1) {
  return window['go']['bindings']['App']['TextBase64Encode'](arg1);
}

export function TextCSVToJSON(arg1) {
  return window['go']['bindings']['App']['TextCSVToJSON'](arg1);
}

export function TextConvertCase(arg1, arg2) {
  return window['go']['bindings']['App']['TextConvertCase'](arg1, arg2);
}

export function TextFormatJSON(arg1, arg2) {
  return window['go']['bindings']['App']['TextFormatJSON'](arg1, arg2);
}

export function TextJSONToCSV(arg1) {
  return window['go']['bindings']['App']['TextJSONToCSV'](arg1);
}

export function TextLorem(arg1, arg2, arg3) {
  return window['go']['bindings']['App']['TextLorem'](arg1, arg2, arg3);
}

export function TextMinifyJSON(arg1) {
  return window['go']['bindings']['App']['TextMinifyJSON'](arg1);
}

export function TextSlug(arg1) {
  return window['go']['bindings']['App']['TextSlug'](arg1);
}

export function TextURLDecode(arg1) {
  return window['go']['bindings']['App']['TextURLDecode'](arg1);
}

export function TextURLEncode(arg1) {
  return window['go']['bindings']['App']['TextURLEncode'](arg1);
}

export function TextWordCount(arg1) {
  return window['go']['bindings']['App']['TextWordCount'](arg1);
}
